CREATE TABLE FORTUNES (ID int, FortuneText varchar(255));
INSERT INTO FORTUNES (ID, FortuneText) VALUES (1, 'Your next commit will break the build.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (2, 'The answers you seek are out there...  on StackOverflow');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (3, 'A project you are involved in will soon come to Clojure.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (4, 'Build the test. Then test the build.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (5, 'Confucius say: SOA make you tired? Better get some REST.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (6, 'In Chinese food and in OSS, purists avoid forks.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (7, 'git clone is an easy way to inherit the mistakes of others.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (8, 'Ignore previous fortune.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (9, 'You will inherit a large sum of... technical debt.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (10, 'Your application will be blessed with good health.  You, on the other hand, should exercise more.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (11, 'You will be blessed with longevity... in all your long running processes.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (12, 'Confucius say: Treat your apps like cattle, not like pets.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (13, 'Confucius say: Today''s best practices are tomorrow''s anti-patterns.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (14, 'Money grows on the tree of persistence.  - Larry Ellison');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (15, 'Linear time is just the default sort order for moments.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (16, 'REST can be beneficial to your application''s health.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (17, 'Protective measures today prevent disasters tomorrow.  Look into Histrix.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (18, 'Remember to always keep a backup.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (19, 'Don''t waste your time on premature optimization.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (20, 'Today is the first day of the rest of your sprint.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (21, '404: Fortune not found');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (22, 'Your code could be better, but it''s good enough.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (23, 'Your next pull request will be accepted.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (24, 'In life and in microservices, you appreciate the simple things.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (25, 'Do what works');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (26, 'How to persist this fortune?  Store it in a cookie.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (27, 'Next time you make a mistake... try command-Z');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (28, 'When life''s problems seems too big, write microservices.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (29, 'In cloud computing and underwear, elasticity is important.');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (30, 'If precious gems is what you seek, check in ~/.gem/ruby/');
INSERT INTO FORTUNES (ID, FortuneText) VALUES (31, 'Confucius say: Man who transports precious gem by train has Ruby on Rails.');